version: "3"
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      POSTGRES_HOST: db
    ports:
      - 8000:8000
    restart: always
