version: "3"
services:
  db:
    # The Postgres database
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./data/${POSTGRES_DIR:-db}:/var/lib/postgresql/data
  make_migrations:
    # Dev command used to create the necessary database migrations
    image: rl-arena
    environment:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - ./core/migrations:/app/core/migrations
    command: [manage.py, makemigrations]
  migrate:
    # Command used to apply the migrations to the database
    image: rl-arena
    environment:
      - POSTGRES_PASSWORD
      - SUPERUSER_USERNAME
      - SUPERUSER_EMAIL
      - SUPERUSER_PASSWORD
      - DJANGO_SECRET_KEY
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=core.settings
    command: [manage.py, migrate]
  web:
    # Web service
    image: rl-arena
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - INVITATION_CODE
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=web.settings
    ports:
      - 8000:8000
    volumes:
      - ./data/media:/app/data/media
    command: [manage.py, runserver, 0.0.0.0:8000]
  builder:
    # Worker service that builds Docker images for the submissions
    image: rl-arena
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=builder.settings
      - LOG_LEVEL=INFO
    volumes:
      - ./data/media:/app/data/media
      # Allows to run docker from inside the container
      - /var/run/docker.sock:/var/run/docker.sock
    command: [-m, builder.main]
  publisher:
    # Worker service that publish to GitHub the public competitors
    image: rl-arena
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - PUBLISHER_REMOTE
      - PUBLISHER_WEB_URL
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=publisher.settings
      - LOG_LEVEL=INFO
      - GIT_SSH_COMMAND=ssh -i /app/data/publish_keys/id_rsa
    volumes:
      - ./data/media:/app/data/media
      - ./data/publish_repo:/app/data/publish_repo
      - ./data/publish_keys:/app/data/publish_keys
    command: [-m, publisher.main]
  smoke_tester:
    # Worker service that test recently-built Docker images for the submissions
    image: rl-arena
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - HOST_CWD
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=smoke_tester.settings
      - LOG_LEVEL=INFO
    volumes:
      - ./data/media:/app/data/media
      # Allows to run docker from inside the container
      - /var/run/docker.sock:/var/run/docker.sock
    command: [-m, smoke_tester.main]
  tournament_manager:
    # Worker service that starts and keep track of tournaments
    image: rl-arena
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=tournament_manager.settings
      - LOG_LEVEL=INFO
    command: [-m, tournament_manager.main]
  duel_runner:
    # Worker service that executes duels
    image: rl-arena
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - HOST_CWD
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - DJANGO_SETTINGS_MODULE=duel_runner.settings
      - LOG_LEVEL=INFO
    volumes:
      - ./data/media:/app/data/media
      # Allows to run docker from inside the container
      - /var/run/docker.sock:/var/run/docker.sock
    command: [-m, duel_runner.main]
