name: rl-arena
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - pip=19.1.1
  - django=2.2.5
  - psycopg2=2.8.3
  - markdown=3.1.1
  - numpy=1.17.2
  - django-crispy-forms=1.8.0
  - pip:
      - pyyaml==5.1.2
      - docker-compose==1.24.1
