# Generated by Django 2.2.5 on 2019-10-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='completed_duels',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='failed_duels',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_duels',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
