# Generated by Django 2.2.5 on 2019-10-22 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='state',
        ),
        migrations.AddField(
            model_name='revision',
            name='image_state',
            field=models.CharField(choices=[('IMAGE_SCHEDULED', ''), ('IMAGE_RUNNING', ''), ('IMAGE_FAILED', ''), ('IMAGE_COMPLETED', '')], default='IMAGE_SCHEDULED', max_length=100),
        ),
        migrations.AddField(
            model_name='revision',
            name='publish_state',
            field=models.CharField(choices=[('PUBLISH_SCHEDULED', ''), ('PUBLISH_RUNNING', ''), ('PUBLISH_FAILED', ''), ('PUBLISH_COMPLETED', '')], default='PUBLISH_SCHEDULED', max_length=100),
        ),
        migrations.AddField(
            model_name='revision',
            name='test_state',
            field=models.CharField(choices=[('TEST_SCHEDULED', ''), ('TEST_RUNNING', ''), ('TEST_FAILED', ''), ('TEST_COMPLETED', '')], default='TEST_SCHEDULED', max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='image_logs',
            field=models.FilePathField(null=True, path='/app/data/media/revision_image_logs/'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='test_logs',
            field=models.FilePathField(null=True, path='/app/data/media/revision_test_logs/'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='zip_file',
            field=models.FileField(upload_to='revisions/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
