# Generated by Django 2.2.5 on 2019-10-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191022_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='publish_state',
            field=models.CharField(choices=[('PUBLISH_SKIPPED', ''), ('PUBLISH_SCHEDULED', ''), ('PUBLISH_RUNNING', ''), ('PUBLISH_FAILED', ''), ('PUBLISH_COMPLETED', '')], max_length=100),
        ),
    ]
