# Generated by Django 2.2.5 on 2019-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191026_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
