# Generated by Django 2.2.5 on 2019-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
