# Generated by Django 2.2.5 on 2019-10-23 20:25

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191022_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='github_source',
            new_name='publish_url',
        ),
        migrations.AddField(
            model_name='revision',
            name='publish_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='publish_error_msg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='revision',
            name='publish_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='zip_file',
            field=models.FileField(upload_to=core.models.zip_file_path, validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
