# Generated by Django 2.2.5 on 2019-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191023_2025'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.UniqueConstraint(fields=('environment', 'name'), name='unique_environment'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('competitor', 'version_number'), name='unique_competitor'),
        ),
    ]
