# Generated by Django 2.2.5 on 2019-11-01 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191101_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(choices=[('CREATING', ''), ('READY', ''), ('STOPPING', ''), ('STOPPED', ''), ('DESTROYED', ''), ('FAILED', '')], default='CREATING', max_length=100)),
                ('creating_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(null=True)),
                ('stopping_at', models.DateTimeField(null=True)),
                ('stopped_at', models.DateTimeField(null=True)),
                ('destroyed_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='duel',
            name='task_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TaskWorker'),
        ),
        migrations.AddField(
            model_name='revision',
            name='test_task_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TaskWorker'),
        ),
    ]
