# Generated by Django 2.2.5 on 2019-10-23 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191023_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='publish_url',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('^https://github.com/')]),
        ),
    ]
