# Generated by Django 2.2.5 on 2019-11-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_revision_publish_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='player_1_logs',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='duel',
            name='player_2_logs',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='revision',
            name='test_player_1_logs',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='revision',
            name='test_player_2_logs',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
