# Generated by Django 2.2.5 on 2019-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl_arena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Will not made public in any way and will not be used for communications', max_length=254, unique=True),
        ),
    ]
