# Generated by Django 2.2.5 on 2019-10-19 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl_arena', '0002_auto_20191019_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='github_commit',
            new_name='github_source',
        ),
        migrations.AlterField(
            model_name='duel',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='logs',
            field=models.FilePathField(null=True, path='/app/data/media/duel_logs/'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='state',
            field=models.CharField(choices=[('SCHEDULED', ''), ('RUNNING', ''), ('FAILED', ''), ('COMPLETED', '')], default='SCHEDULED', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image_logs',
            field=models.FilePathField(null=True, path='/app/data/media/submission_image_logs/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('WAITING_BUILD', ''), ('BUILDING', ''), ('BUILD_FAILED', ''), ('WAITING_SMOKE_TEST', ''), ('TESTING', ''), ('FAILED_SMOKE_TEST', ''), ('READY', '')], default='WAITING_BUILD', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_logs',
            field=models.FilePathField(null=True, path='/app/data/media/submission_test_logs/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='zip_file',
            field=models.FileField(upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='state',
            field=models.CharField(choices=[('RUNNING', ''), ('FAILED', ''), ('COMPLETED', '')], default='RUNNING', max_length=100),
        ),
    ]
