version: "2.4"
services:
  run_duel:
    # Command to execute a duel
    image: rl-arena
    volumes:
      # Weird hack alert: we will start a docker from inside a docker here
      # This means that:
      # 1. the mount path will be resolved by docker-compose inside the container
      # 2. the mount will be created by docker on the host machine
      # That's why we need to carry the host working directory around
      - $HOST_CWD/data/media:/app/data/media
      # Allows to run docker from inside the container
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DUEL_IMAGE_1
      - DUEL_IMAGE_2
      - DUEL_ENVIRONMENT
      - DUEL_OUTPUT_FILE
      - DUEL_NAMESPACE
      - LOG_LEVEL=INFO
    command: [-m, run_duel.main]
    networks: [duel_1, duel_2]
  player_1:
    image: ${PLAYER_IMAGE:-}
    cpus: ${PLAYER_CPU_LIMIT:-0}
    mem_limit: ${PLAYER_MEMORY_LIMIT:-}
    networks: [duel_1]
  player_2:
    image: ${PLAYER_IMAGE:-}
    cpus: ${PLAYER_CPU_LIMIT:-0}
    mem_limit: ${PLAYER_MEMORY_LIMIT:-}
    networks: [duel_2]
networks:
  # Networks used to keep dueling players isolated
  duel_1:
  duel_2:
